name: Build Test Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code 
      uses: actions/checkout@v4
    - name: Set Node.js             
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install
    - name: Start Backend
      run: npm run server &
    - name: Start Frontend                    
      run: npm run start &
    - name: Start Tests                   
      run: npm run test
